### ISSUE TITLE
[bug]: Input text area issue

### ISSUE THREAD

**Issue by ghpranav** [ghpranav/VocabGenie#3]
### Description

The text overflows on the Submit button of the input text area.

### Reproduction steps

1. Go to [VocabGenie](https://vocabgenie.vercel.app/), preferably in mobile
2. Click on any deck
3. Input a lengthy text as the meaning of the word

### Screenshots

![image](https://github.com/ghpranav/VocabGenie/assets/31174544/4b0edb7b-c5ac-4e1f-bcee-c503b8f60b32)

**Comment by prithvi206** [comment]
@ghpranav I have create a pull request for this bug. Do let me know rules to follow for contribution.

**Comment by ghpranav** [comment]
@prithvi206 thanks for taking up this issue, will assign it to you. You can go over [CONTRIBUTING.md](https://github.com/ghpranav/VocabGenie/blob/main/.github/%20CONTRIBUTING.md) for more info
